version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_REPLICATION_MODE=master
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z.fips
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminPassword
    command: server --console-address ":9001" /data

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bytubeDB
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  nginx-rtmp:
    build:
      context: ./nginx/
    ports:
      - "1935:1935"
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf


volumes:
  minio_storage: {}
  db:
    driver: local