/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StreamOptionsForm: typeof import('./components/StreamOptionsForm.vue')['default']
    StreamPreview: typeof import('./components/StreamPreview.vue')['default']
    VideoPreview: typeof import('./components/VideoPreview.vue')['default']
    VideoUpload: typeof import('./components/video-upload.vue')['default']
  }
}
