/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>>,
    '/author/[authorId]': RouteRecordInfo<'/author/[authorId]', '/author/:authorId', { authorId: ParamValue<true> }, { authorId: ParamValue<false> }>,
    '/reset_password': RouteRecordInfo<'/reset_password', '/reset_password', Record<never, never>, Record<never, never>>,
    '/stream/[streamId]': RouteRecordInfo<'/stream/[streamId]', '/stream/:streamId', { streamId: ParamValue<true> }, { streamId: ParamValue<false> }>,
    '/userProfile': RouteRecordInfo<'/userProfile', '/userProfile', Record<never, never>, Record<never, never>>,
    '/video/[videoId]': RouteRecordInfo<'/video/[videoId]', '/video/:videoId', { videoId: ParamValue<true> }, { videoId: ParamValue<false> }>,
  }
}
